/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.BadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.Treasure;
import NapakalakiGame.TreasureKind;
import java.awt.Label;
import java.util.ArrayList;
import java.awt.TextField;
import javax.swing.JPanel;
/**
 *
 * @author adritake
 */
public class BadConsequenceView extends javax.swing.JPanel {

    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
        NVisibleTreasures.setText("0");

        NHiddenTreasures.setText("0");
    }
    
    public void setBadConsequence( BadConsequence model){
        
        BadConsequenceText.setText( model.getText() );
        
        if( model instanceof DeathBadConsequence ){
        
            Death.setText( "Sí" );
            Death.setVisible(true);
            DeathLabel.setVisible(true);
            LevelsLabel.setVisible(false);
            Levels.setVisible(false);
            NVisibleTreasuresLabel.setVisible(false);
            NHiddenTreasuresLabel.setVisible(false);
            NVisibleTreasures.setVisible(false);
            NHiddenTreasures.setVisible(false);
            SpecificHiddenTreasuresLabel.setVisible(false);
            SpecificHiddenTreasures.setVisible(false);
            SpecificVisibleTreasuresLabel.setVisible(false);
            SpecificVisibleTreasures.setVisible(false);

        }
        else if( model instanceof NumericBadConsequence){
            
            Death.setVisible(false);
            DeathLabel.setVisible(false);
            LevelsLabel.setVisible(true);
            Levels.setVisible(true);
            SpecificHiddenTreasuresLabel.setVisible(false);
            SpecificHiddenTreasures.setVisible(false);
            SpecificVisibleTreasuresLabel.setVisible(false);
            SpecificVisibleTreasures.setVisible(false);
            NVisibleTreasuresLabel.setVisible(true);
            NHiddenTreasuresLabel.setVisible(true);
            NVisibleTreasures.setVisible(true);
            NHiddenTreasures.setVisible(true);
            
            Levels.setText( Integer.toString( model.getLevels() ));
            NVisibleTreasures.setText( Integer.toString( ((NumericBadConsequence) model).getnVisible() ));
            NHiddenTreasures.setText( Integer.toString( ((NumericBadConsequence) model).getnHidden() ));
            
            
        }
        
        else if( model instanceof SpecificBadConsequence ){
            
            Death.setVisible(false);
            DeathLabel.setVisible(false);
            LevelsLabel.setVisible(true);
            Levels.setVisible(true);
            NVisibleTreasuresLabel.setVisible(false);
            NHiddenTreasuresLabel.setVisible(false);
            NVisibleTreasures.setVisible(false);
            NHiddenTreasures.setVisible(false);
            SpecificHiddenTreasuresLabel.setVisible(true);
            SpecificHiddenTreasures.setVisible(true);
            SpecificVisibleTreasuresLabel.setVisible(true);
            SpecificVisibleTreasures.setVisible(true);
            
            Levels.setText( Integer.toString( model.getLevels() ));
            this.fillTreasurePanel(SpecificVisibleTreasures, ((SpecificBadConsequence) model).getTvisible());
            this.fillTreasurePanel(SpecificHiddenTreasures, ((SpecificBadConsequence) model).getThidden());
            
        }
        
        repaint();
        
    }
    
  private void fillTreasurePanel (JPanel aPanel, ArrayList<TreasureKind> aList){
       
       aPanel.removeAll();
       
       for( TreasureKind t: aList){
           
           Label lab = new Label();
           lab.setText( t.toString() );
           lab.setVisible(true);
           aPanel.add(lab);
           
       }
       
       aPanel.repaint();
       aPanel.revalidate();
       
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField2 = new java.awt.TextField();
        BadConsequenceText = new java.awt.TextField();
        LevelsLabel = new javax.swing.JLabel();
        DeathLabel = new javax.swing.JLabel();
        Levels = new java.awt.Label();
        Death = new java.awt.Label();
        NVisibleTreasuresLabel = new javax.swing.JLabel();
        NHiddenTreasuresLabel = new javax.swing.JLabel();
        NVisibleTreasures = new java.awt.Label();
        NHiddenTreasures = new java.awt.Label();
        SpecificVisibleTreasuresLabel = new javax.swing.JLabel();
        SpecificHiddenTreasuresLabel = new javax.swing.JLabel();
        SpecificVisibleTreasures = new javax.swing.JPanel();
        SpecificHiddenTreasures = new javax.swing.JPanel();

        textField2.setText("textField2");

        BadConsequenceText.setText("textField1");
        BadConsequenceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadConsequenceTextActionPerformed(evt);
            }
        });

        LevelsLabel.setText("Niveles:");

        DeathLabel.setText("Muerte:");

        Levels.setText("label1");

        Death.setText("label2");

        NVisibleTreasuresLabel.setText("Tesoros Visibles:");

        NHiddenTreasuresLabel.setText("Tesoros Ocultos:");

        NVisibleTreasures.setText("label1");

        NHiddenTreasures.setText("label2");

        SpecificVisibleTreasuresLabel.setText("Tesoros Visibles");

        SpecificHiddenTreasuresLabel.setText("Tesoros Ocultos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BadConsequenceText, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(DeathLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Death, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LevelsLabel)
                                    .addGap(25, 25, 25)
                                    .addComponent(Levels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NHiddenTreasuresLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NVisibleTreasuresLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SpecificVisibleTreasures, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpecificVisibleTreasuresLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SpecificHiddenTreasuresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpecificHiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BadConsequenceText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LevelsLabel))
                    .addComponent(Levels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DeathLabel)
                            .addComponent(Death, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NVisibleTreasuresLabel)
                            .addComponent(NVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(NHiddenTreasuresLabel))
                    .addComponent(NHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpecificVisibleTreasuresLabel)
                    .addComponent(SpecificHiddenTreasuresLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SpecificHiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SpecificVisibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BadConsequenceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadConsequenceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BadConsequenceTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField BadConsequenceText;
    private java.awt.Label Death;
    private javax.swing.JLabel DeathLabel;
    private java.awt.Label Levels;
    private javax.swing.JLabel LevelsLabel;
    private java.awt.Label NHiddenTreasures;
    private javax.swing.JLabel NHiddenTreasuresLabel;
    private java.awt.Label NVisibleTreasures;
    private javax.swing.JLabel NVisibleTreasuresLabel;
    private javax.swing.JPanel SpecificHiddenTreasures;
    private javax.swing.JLabel SpecificHiddenTreasuresLabel;
    private javax.swing.JPanel SpecificVisibleTreasures;
    private javax.swing.JLabel SpecificVisibleTreasuresLabel;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
