/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;
import javax.swing.JOptionPane;


/**
 *
 * @author pablo
 */
public class NapakalakiView extends javax.swing.JFrame {
    Napakalaki napakalakiModel;
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }
    
    public void setNapakalaki(Napakalaki model){
        napakalakiModel = model; 
        CurrentMonster.setMonster( model.getCurrentMonster() );
        CurrentMonster.setVisible(false);
        CurrentPlayer.setPlayer( model.getCurrentPlayer() );
        CurrentPlayer.setNapakalaki( model );
        CurrentPlayer.setEnabledButtoms(true,false);
        NextTurn.setVisible(false);
        
        Combat.setVisible(false);
   
        //JOptionPane.showMessageDialog(null, "PRUEBA", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        
        
      
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MeetTheMonster = new javax.swing.JButton();
        Combat = new javax.swing.JButton();
        NextTurn = new javax.swing.JButton();
        CurrentPlayer = new GUI.PlayerView();
        CurrentMonster = new GUI.MonsterView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MeetTheMonster.setText("Meet the Monster");
        MeetTheMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeetTheMonsterActionPerformed(evt);
            }
        });

        Combat.setText("Combat");
        Combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombatActionPerformed(evt);
            }
        });

        NextTurn.setText("Next Turn");
        NextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextTurnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CurrentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(MeetTheMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(NextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Combat, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(CurrentMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(459, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(CurrentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MeetTheMonster)
                    .addComponent(NextTurn)
                    .addComponent(Combat))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombatActionPerformed
        // TODO add your handling code here:
       
       Combat.setVisible(false);
       
       if( napakalakiModel.developCombat() == CombatResult.WINGAME ){
           
           NextTurn.setVisible(false);
           
           CurrentPlayer.setEnabledButtoms( false,false );
           CurrentPlayer.setPlayer( napakalakiModel.getCurrentPlayer());
           JOptionPane.showMessageDialog(null, "HAS GANADO!!!!", "", JOptionPane.INFORMATION_MESSAGE);
       }
       else{
            NextTurn.setVisible(true);           
            CurrentPlayer.setEnabledButtoms( true,true );
            CurrentPlayer.setPlayer( napakalakiModel.getCurrentPlayer());
       }
       repaint();
       
    }//GEN-LAST:event_CombatActionPerformed

    private void MeetTheMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeetTheMonsterActionPerformed
        // TODO add your handling code here:
        CurrentMonster.setVisible(true);
        CurrentPlayer.setEnabledButtoms( false,false );
        Combat.setVisible(true);
        MeetTheMonster.setVisible(false);
        repaint();
    }//GEN-LAST:event_MeetTheMonsterActionPerformed

    private void NextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextTurnActionPerformed
        // TODO add your handling code here:
        
        if(napakalakiModel.nextTurn()){
            
            setNapakalaki(napakalakiModel);
            CurrentPlayer.setEnabledButtoms(  true,false );
            MeetTheMonster.setVisible(true);
            
        }
        else
            
           JOptionPane.showMessageDialog(null, "No puedes pasar de turno", "", JOptionPane.INFORMATION_MESSAGE);
        
        
        repaint();
        
    }//GEN-LAST:event_NextTurnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Combat;
    private GUI.MonsterView CurrentMonster;
    private GUI.PlayerView CurrentPlayer;
    private javax.swing.JButton MeetTheMonster;
    private javax.swing.JButton NextTurn;
    // End of variables declaration//GEN-END:variables
}
