/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.BadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.TreasureKind;
import java.awt.Label;
import java.awt.TextField;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author adritake
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }
    
    public void setPendingBadConsequence( BadConsequence model){
        
        
        if( model.isEmpty() ){
            
            NothingLabel.setVisible(true);
            SpecificHiddenTreasures.setVisible(false);
            SpecificVisibleTreasures.setVisible(false);
            NHiddenTreasure.setVisible(false);
            NVisibleTreasure.setVisible(false);
            VisibleTreasuresLabel.setVisible(false);
            HiddenTreasuresLabel.setVisible(false);
            
        }
        if( model instanceof NumericBadConsequence){
            
            SpecificHiddenTreasures.setVisible(false);
            SpecificVisibleTreasures.setVisible(false);
            NothingLabel.setVisible(false);
            NHiddenTreasure.setText( Integer.toString(((NumericBadConsequence)model).getnHidden()));
            NVisibleTreasure.setText( Integer.toString(((NumericBadConsequence)model).getnVisible()));
            VisibleTreasuresLabel.setVisible(true);
            HiddenTreasuresLabel.setVisible(true);
            NHiddenTreasure.setVisible(true);
            NVisibleTreasure.setVisible(true);
            
        }
        else if( model instanceof SpecificBadConsequence){
            
            NHiddenTreasure.setVisible(false);
            NVisibleTreasure.setVisible(false);
            SpecificHiddenTreasures.setVisible(true);
            SpecificVisibleTreasures.setVisible(true);
            NothingLabel.setVisible(false);
            this.fillTreasurePanel(SpecificHiddenTreasures, ((SpecificBadConsequence) model).getThidden());
            this.fillTreasurePanel(SpecificVisibleTreasures, ((SpecificBadConsequence) model).getTvisible());
            VisibleTreasuresLabel.setVisible(true);
            HiddenTreasuresLabel.setVisible(true);
            
        }
        
        this.repaint();
       
        
    }
    
     private void fillTreasurePanel (JPanel aPanel, ArrayList<TreasureKind> aList){
       
       aPanel.removeAll();
       
       for( TreasureKind t: aList){
           
           Label lab = new Label();
           lab.setText( t.toString() );
           lab.setVisible(true);
           aPanel.add(lab);
           
       }
       
       aPanel.repaint();
       aPanel.revalidate();
       
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VisibleTreasuresLabel = new javax.swing.JLabel();
        HiddenTreasuresLabel = new javax.swing.JLabel();
        NVisibleTreasure = new java.awt.Label();
        NHiddenTreasure = new java.awt.Label();
        BadConsequenceLabel = new javax.swing.JLabel();
        NothingLabel = new javax.swing.JLabel();
        SpecificVisibleTreasures = new javax.swing.JPanel();
        SpecificHiddenTreasures = new javax.swing.JPanel();

        VisibleTreasuresLabel.setText("Tesoros Visibles:");

        HiddenTreasuresLabel.setText("Tesoros Ocultos:");

        NVisibleTreasure.setText("label1");

        NHiddenTreasure.setText("label2");

        BadConsequenceLabel.setText("Mal Rollo Pendiente");

        NothingLabel.setText(":   Ninguno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(BadConsequenceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(NothingLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VisibleTreasuresLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NVisibleTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SpecificVisibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HiddenTreasuresLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NHiddenTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SpecificHiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BadConsequenceLabel)
                    .addComponent(NothingLabel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NVisibleTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NHiddenTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VisibleTreasuresLabel)
                            .addComponent(HiddenTreasuresLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpecificVisibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(SpecificHiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BadConsequenceLabel;
    private javax.swing.JLabel HiddenTreasuresLabel;
    private java.awt.Label NHiddenTreasure;
    private java.awt.Label NVisibleTreasure;
    private javax.swing.JLabel NothingLabel;
    private javax.swing.JPanel SpecificHiddenTreasures;
    private javax.swing.JPanel SpecificVisibleTreasures;
    private javax.swing.JLabel VisibleTreasuresLabel;
    // End of variables declaration//GEN-END:variables
}
